server:
  port: 8082
spring:
  profiles:
    active: local

  devtools:
    livereload:
      port: 35730
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
debug: true